# NumPy Reductions / Cumulative Ops / Linear Algebra — Practice Questions


1) Given a:
Compute the total of all elements in `a`. Then compute the total again but keep the result as a 2D array with shape `(1, 1)`.


In [3]:
import numpy as np
a = np.array([3, -1, 4, 0, 2])
np.sum(a)
np.sum(a, keepdims=True)

array([8])

2) Given:
```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])
```
Compute the column-wise totals (one total per column). Also compute the row-wise totals (one total per row).


In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.sum(a, axis=0, keepdims=True))

print(np.sum(a, axis=1, keepdims=True))



[[5 7 9]]
[[ 6]
 [15]]


3) Given:
```python
a = np.array([[ 2, -1,  0],
              [ 3,  5, -2]])
```
Compute the product of all elements in `a`. Then compute the product along each row.


In [7]:
a = np.array([[ 2, -1,  0],
              [ 3,  5, -2]])

np.prod(a)
np.prod(a, axis=1, keepdims=True) # along dim 1

array([[  0],
       [-30]])

4) Given:
```python
a = np.array([10, 12, 14, 16])
```
Compute the average value of `a`.

In [8]:
a = np.array([10, 12, 14, 16])
np.mean(a)

np.float64(13.0)

5) Given:
```python
a = np.array([[1, 1, 2],
              [3, 5, 8]])
```
Compute the mean of each column. Then compute the mean of each row.


In [9]:
a = np.array([[1, 1, 2],
              [3, 5, 8]])

np.mean(a, axis=0, keepdims=True)

array([[2., 3., 5.]])






6) Given:
```python
a = np.array([1, 2, 3, 4, 5])
```
Compute the standard deviation of `a` using the population definition. Then compute it again using the sample definition.

7) Given:
```python
a = np.array([[2, 2, 2],
              [2, 5, 8]])
```
Compute the variance of all elements in `a` using the population definition. Then compute the variance of each column using the sample definition.

8) Given:
```python
a = np.array([[ 9,  3,  7],
              [ 2, 10, -1]])
```
Find the smallest value in the entire array. Then find the largest value in each row.

9) Given:
```python
a = np.array([5, 1, 9, 2, 9])
```
Find the position (index) of the first occurrence of the maximum value in `a`. Also find the position of the minimum value.

10) Given:
```python
a = np.array([[4, 7, 1],
              [6, 0, 5]])
```
Find the index of the minimum value in the flattened array. Then find the index of the maximum value within each row.

11) Given:
```python
a = np.array([3, 100, 4, 5, 6])
```
Compute the median of `a`.

12) Given:
```python
a = np.array([[1, 50, 2, 3],
              [9,  8, 7, 6]])
```
Compute the median of each row. Then compute the median of each column.

13) Given:
```python
a = np.array([0, 0, 0, 1, 0])
```
Decide whether **any** element of `a` is nonzero/truthy. Also decide whether **all** elements of `a` are nonzero/truthy.

14) Given:
```python
a = np.array([[True,  True, False],
              [True,  True,  True]])
```
Check whether each column has **any** `True`. Then check whether each row has **all** `True`.

15) Given:
```python
a = np.array([[0, 2, 0],
              [0, 0, 0]])
```
Treat `a` as a truthy/falsey array. Determine if there exists at least one truthy value in the whole array. Then determine if all rows contain at least one truthy value.

16) Given:
```python
a = np.array([1, 2, 3, 4])
```
Compute the running totals (prefix sums) of `a`.

17) Given:
```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])
```
Compute the cumulative sum along columns (down each column). Then compute the cumulative sum along rows (across each row).

18) Given:
```python
a = np.array([2, 3, 0, 4])
```
Compute the running products of `a`.

19) Given:
```python
a = np.array([[1, 2, 3],
              [2, 2, 2]])
```
Compute the cumulative product across each row. Then compute the cumulative product down each column.

20) Given:
```python
a = np.array([1, -2, 3])
b = np.array([4,  0, -1])
```
Compute the dot product of `a` and `b`.

21) Given:
```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
```
Compute the result of multiplying `a` by `b` in the linear-algebra sense to produce a length-2 output.

22) Given:
```python
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
```
Compute the matrix product `a` times `b`.

23) Given:
```python
a = np.array([[2, 0, 1],
              [1, 3, 2]])
b = np.array([[1, 2],
              [0, 1],
              [4, 0]])
```
Compute the matrix product of `a` and `b`. What is the resulting shape?

24) Given:
```python
a = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])
b = np.array([[ -1,  0,  2],
              [  3,  1,  0],
              [  0,  4,  1]])
```
Compute the matrix product `a` times `b`. Then compute `b` times `a`. Verify whether the two results are the same.

25) Given:
```python
a = np.array([[3, 1, 2],
              [9, 0, 4],
              [6, 5, 8]])
```
Find, for each column, the index of the largest element. Also find, for each row, the index of the smallest element.

26) Given:
```python
a = np.array([[-2, -1, -3],
              [ 0,  5,  4]])
```
Compute the minimum and maximum of each row. Then compute the minimum and maximum of the entire array.

27) Given:
```python
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
```
Compute:
- the sum of each column
- the product of each column
- the mean of each column
(three separate results)

28) Given:
```python
a = np.array([[1, 2, 3, 4],
              [5, 0, 7, 8]])
```
Compute the running totals across each row. Then compute the running totals down each column.

29) Given:
```python
a = np.array([1, 2, 3, 4, 5, 6])
```
Compute the index of the maximum element when considering `a` as a single flat array. Then reshape `a` into shape `(2, 3)` (in your code) and compute the index of the maximum within each row.

30) Given:
```python
a = np.array([[1, 1, 1],
              [1, 1, 2],
              [1, 2, 2]])
```
Compute the median of the entire array. Then compute the median of each row.

31) Given:
```python
a = np.array([[True,  True,  True],
              [True,  False, True]])
```
Decide whether all elements in the entire array are `True`. Then decide whether any element in each row is `True`.

32) Given:
```python
a = np.array([0, 0, 0, 0])
```
Treat `a` as truthy/falsey values. Determine whether any element is truthy and whether all elements are truthy.

33) Given:
```python
a = np.array([2, 2, 2, 2, 2])
```
Compute the variance and standard deviation of `a` (population definitions). What do you expect the result to be and why?

34) Given:
```python
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])
b = np.array([[1, 0, 0],
              [0, 1, 0]])
```
Compute the matrix product `b` times `a`. What is the resulting shape? (Do not transpose anything unless you choose to in your own code.)

35) Given:
```python
a = np.array([1, 2, 3])
b = np.array([[10],
              [20],
              [30]])
```
Compute the matrix product of `a` and `b` (in a way that is valid). Describe the resulting shape.

36) Given:
```python
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
```
Compute the sum of the diagonal elements using a single expression built from a matrix multiplication / dot-style operation (avoid loops).

37) Given:
```python
a = np.array([[ 1, -1,  2],
              [ 0,  3, -2]])
```
Compute:
- the index of the minimum value in the flattened array
- the index of the minimum value for each column

38) Given:
```python
a = np.array([[1, 2, 3, 4]])
```
Compute the cumulative product across the only row. Then compute the cumulative sum across the only row. (Return both results.)

39) Given:
```python
a = np.array([[2, 3],
              [4, 5]])
```
Compute the product of all entries. Then compute the product along the column axis.

40) Given:
```python
a = np.array([3, 1, 4, 1, 5, 9])
```
Compute:
- the sum of all elements
- the mean
- the variance (sample definition)
- the standard deviation (sample definition)
Return the four values.

41) Given:
```python
a = np.array([[0, 1, 0],
              [2, 0, 3],
              [0, 0, 0]])
```
Treat the array as truthy/falsey. Determine:
- whether any element in each row is truthy
- whether all elements in each column are truthy

42) Given:
```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[1, 0],
              [0, 1],
              [1, 1]])
```
Compute the matrix product of `a` and `b`. Then compute the sum of all elements in the resulting matrix.

43) Given:
```python
a = np.array([5, -2, 7, -2, 5])
```
Find the median. Then find the index of the first minimum value. Then find the index of the first maximum value.

44) Given:
```python
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 0]])
```
Compute the argmax along each column. Using those indices, verify in your own code that they actually point to the column-wise maxima.

45) Given:
```python
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
```
Compute two different scalar results:
- a dot-style multiplication result
- a sum-after-elementwise-multiplication result
Confirm that they match.